### ISSUE TITLE
Achieve consensus on abstract designs

### ISSUE THREAD

**Issue by c-to-the-fazzy** [c-to-the-fazzy/cardiathena#4]
Discuss the relevant wiki pages and inspect the base classes and examples.

**Comment by davidjha** [comment]
Would scoring information be needed, and maybe get stored along with the state_history, action_history, and agent_list? 
If so a abstract get_score() method in the adjudicator

Should there be an inclusion of a base database class? Maybe a database base class doesn’t belong in this document since it’s not strictly game-play related. In any case, a database class might need to assign an uuid for each game manager to link to its own state_history, action_history, and agent_list.

**Comment by c-to-the-fazzy** [comment]
@davidjha 

In my mind, a game's score is part of the state of the game.  Adding it there will keep it tracked automatically in the `state_history` list.  I added a `scores` data member to the `TicTacToeState` class.  The score is zero for both players throughout the entire game, but when a game is finished is updated to one of `[0, 1]`, `[1, 0]`, or `[0.5, 0.5]`.  I also updated the adjudicator's `step_game()` method with logic to update the score.  Please review.  

What would be the purpose of a `get_score()` method on the adjudicator?  (I'm not saying there _definitely_ shouldn't be such a method, I'm just trying to see what ideas are in your mind!)

I do not think there needs to be a class for the database(s).  A database is (in my admittedly limited understanding) usually a daemon or service running either locally or on the network.  Our code will connect to that daemon/service (i.e. form a Client) and then execute write operations.  The implementation of the connection is pending all sorts of details like do we use SQL, or MongoDB, or what.  

However, the `save_game()` method of the `GameManager` is what (I imagine?) will likely parse its `state_history` and `action_history` lists, encode them into a DB specification, and execute the write operations to the DB.

**Comment by davidjha** [comment]
I think I was over-complicating things, and didn't quite finish my thought. 
"If so a abstract get_score() method in the adjudicator..." 
My reasoning for the inclusion of get_score() is for the agents to be able to see the scores, and the way to do that was for the adjudicator to pass along that information. I see that it is as simple as to include and update the scoring information along with the state.
