### ISSUE TITLE
Turn-Paint-Diagram-to-Professional-Diagram

### ISSUE THREAD

**Issue by aphelps4** [c-to-the-fazzy/cardiathena#45]
# Description

A paint diagram of the main idea of the project was made for confirmation. That diagram should now be made in a more professional manner and added to our documentation.

# Tasks

- [x] Make the diagram
- [x] Add it to documentation (possibly game manager document)

**Comment by irobert4** [comment]
@aphelps4 Michael and I have made your paint diagram.  You can see it on our google drive (see group chat) or find it under:

https://github.com/c-to-the-fazzy/cardiathena/tree/master/documentation/img

called "AngelasLovelyPaintDiagram.pdf"
