### ISSUE TITLE
Finish Card-Counting Documentation

### ISSUE THREAD

**Issue by aphelps4** [c-to-the-fazzy/cardiathena#5]
Figure out formulas to discover probability of players having certain cards/suits based on knowledge of who is void of which suits, which cards have been played, and which players still need to play for the current trick.

- [x] post link to research in wiki documentation
- [ ] codify algorithm in wiki documentation
- [ ] create function to update knowledge of whether other players are void of a suit or not
  - [ ]  determine need of this function
  - [ ]  create pseudo-code for this function

**Comment by kruzaavn** [comment]
@aphelps4 how has this been going for you? can you post any links to some of your sources yet?

**Comment by msomarri** [comment]
Closing this issue for now. Possibly will reopen once we have develop the minimizing agent.
