### ISSUE TITLE
Finish Base Agent

### ISSUE THREAD

**Issue by aphelps4** [c-to-the-fazzy/cardiathena#7]
# Description

Finish the base agent in the Agent Design Document by figuring out what it does with the data it receives from the adjudicator and how to update knowledge.

# Tasks

Include checkboxes for the sub tasks that need to be accomplished in order to mark the Development Task is complete e.g.

- [ ] create pseudo-code for the get_action(partial_state : State) function on the base agent

**Comment by davidjha** [comment]
Moved non base agent parts to Issue #5. So closing this.
